# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-19 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180418_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043f\u0440\u043e\u0434\u0443\u043a\u0442\u0430')),
                ('level', models.PositiveIntegerField(unique=True, verbose_name='\u0423\u0440\u043e\u0432\u0435\u043d\u044c \u043f\u0440\u043e\u0434\u0443\u043a\u0442\u0430')),
                ('price', models.PositiveIntegerField(verbose_name='\u0426\u0435\u043d\u0430 \u043f\u0440\u043e\u0434\u0443\u043a\u0442\u0430')),
            ],
            options={
                'verbose_name': '\u041f\u0440\u043e\u0434\u0443\u043a\u0442',
                'verbose_name_plural': '\u041f\u0440\u043e\u0434\u0443\u043a\u0442\u044b',
            },
        ),
        migrations.AlterField(
            model_name='transactionkeys',
            name='key',
            field=models.UUIDField(default=uuid.UUID('be9f05e5-ed62-4672-8b29-495467cd41de')),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Products', verbose_name='\u0422\u0435\u043a\u0443\u0449\u0438\u0439 \u0443\u0440\u043e\u0432\u0435\u043d\u044c'),
        ),
    ]
