# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-19 13:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180419_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionkeys',
            name='key',
            field=models.UUIDField(default=uuid.UUID('fd39ba61-5da0-485c-a1f9-41550a3f4d65')),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Products', verbose_name='\u0422\u0435\u043a\u0443\u0449\u0438\u0439 \u0443\u0440\u043e\u0432\u0435\u043d\u044c'),
        ),
        migrations.AlterField(
            model_name='user',
            name='related_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='\u0420\u0435\u0444\u0435\u0440\u0430\u043b\u044b'),
        ),
    ]
