# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180419_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionkeys',
            name='key',
            field=models.CharField(max_length=255, null=True, verbose_name='ID \u0442\u0440\u0430\u043d\u0437\u0430\u043a\u0446\u0438\u0438'),
        ),
    ]
