# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180420_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobilnik',
            field=models.CharField(max_length=255, null=True, verbose_name='\u041c\u043e\u0431\u0438\u043b\u044c\u043d\u0438\u043a \u043a\u043e\u0448\u0435\u043b\u0435\u043a'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=255, null=True, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0442\u0435\u043b\u0435\u0444\u043e\u043d\u0430'),
        ),
    ]
