# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180420_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionkeys',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='\u041f\u043e\u0434\u0442\u0432\u0435\u0440\u0436\u0434\u0435\u043d'),
        ),
    ]
