# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_transactionkeys_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionkeys',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Products', verbose_name='\u0417\u0430 \u0442\u043e\u0432\u0430\u0440'),
        ),
    ]
