# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-21 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_transactionkeys_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/product_images'),
        ),
    ]
