# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-23 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_products_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u043e\u0446\u0441\u0435\u0442\u0438')),
                ('link', models.URLField(verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 \u0441\u043e\u0446\u0441\u0435\u0442\u044c')),
                ('icon', models.FileField(upload_to=b'', verbose_name='\u0418\u043a\u043e\u043d\u043a\u0430')),
                ('icon_code', models.CharField(help_text='\u041a\u043e\u0434 \u0432\u044b \u043c\u043e\u0436\u0435\u0442\u0435 \u0432\u0437\u044f\u0442\u044c \u043d\u0430 \u0441\u0430\u0439\u0442\u0435 fontawesome.io/icons', max_length=255, verbose_name='\u041a\u043e\u0434 \u0438\u043a\u043e\u043d\u043a\u0438')),
            ],
            options={
                'verbose_name': '\u0421\u0441\u044b\u043b\u043a\u0430',
                'verbose_name_plural': '\u0421\u0441\u044b\u043b\u043a\u0438 \u043d\u0430 \u0441\u043e\u0446\u0441\u0435\u0442\u0438',
            },
        ),
    ]
