# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_sociallinks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionkeys',
            name='is_confirmed',
        ),
        migrations.AddField(
            model_name='transactionkeys',
            name='is_confirmed_by_admin',
            field=models.BooleanField(default=False, verbose_name='\u041f\u043e\u0434\u0442\u0432\u0435\u0440\u0436\u0434\u0435\u043d \u0430\u0434\u043c\u0438\u043d\u043e\u043c'),
        ),
        migrations.AddField(
            model_name='transactionkeys',
            name='is_confirmed_by_user',
            field=models.BooleanField(default=False, verbose_name='\u041f\u043e\u0434\u0442\u0432\u0435\u0440\u0436\u0434\u0435\u043d \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u0435\u043c'),
        ),
    ]
