# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 19:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20180426_0009'),
        ('main', '0011_agree'),
    ]

    operations = [
    ]
