# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-04 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20180502_1146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ['timestamp'], 'verbose_name': '\u0421\u043b\u0430\u0439\u0434\u0435\u0440', 'verbose_name_plural': '\u0420\u0430\u0437\u0434\u0435\u043b \u0441\u043b\u0430\u0439\u0434\u043e\u0432'},
        ),
        migrations.AddField(
            model_name='products',
            name='price1',
            field=models.PositiveIntegerField(default=150, verbose_name='\u0426\u0435\u043d\u0430 \u043f\u0440\u043e\u0434\u0443\u043a\u0446\u0438\u0438'),
        ),
    ]
