# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-08 13:58
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20180504_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
    ]
