# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-27 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_products_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionkeys',
            name='key_for_admin',
        ),
    ]
