# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-07 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_transactionkeys_key_for_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionkeys',
            name='key_for_user',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='ID \u0442\u0440\u0430\u043d\u0437\u0430\u043a\u0446\u0438\u0438 \u0434\u043b\u044f \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f'),
        ),
    ]
