# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-15 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20180716_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(choices=[('1', '\u0427\u0443\u0439'), ('2', '\u041e\u0448'), ('3', '\u0411\u0430\u0442\u043a\u0435\u043d'), ('4', '\u0414\u0436\u0430\u043b\u0430\u043b-\u0410\u0431\u0430\u0434'), ('5', '\u0418\u0441\u0441\u044b\u043a-\u041a\u0443\u043b\u044c'), ('6', '\u041d\u0430\u0440\u044b\u043d'), ('6', '\u0422\u0430\u043b\u0430\u0441')], max_length=255, null=True, verbose_name='\u041e\u0431\u043b\u0430\u0441\u0442\u044c'),
        ),
    ]
