# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-25 15:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_gallery_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='\u0421\u043a\u043e\u043b\u044c\u043a\u043e')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u041f\u0435\u0440\u0435\u0432\u043e\u0434 \u0431\u0430\u043b\u043b\u043e\u0432',
                'verbose_name_plural': '\u041f\u0435\u0440\u0435\u0432\u043e\u0434\u044b \u0431\u0430\u043b\u043b\u043e\u0432',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='\u0411\u0430\u043b\u043b\u044b'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL, verbose_name='\u041e\u0442 \u043a\u043e\u0433\u043e'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL, verbose_name='\u041a\u043e\u043c\u0443'),
        ),
    ]
