# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-27 10:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20180827_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='from_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL, verbose_name='\u041e\u0442 \u043a\u043e\u0433\u043e'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wallet_id',
            field=models.CharField(default=b'E7DEC2C4', max_length=8),
        ),
    ]
