# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-04 13:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20180827_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_id', models.CharField(max_length=255, verbose_name='\u041a\u043b\u044e\u0447 \u0442\u0440\u0430\u043d\u0437\u0430\u043a\u0446\u0438\u0438')),
                ('date', models.DateField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('sum', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='\u0421\u0443\u043c\u043c\u0430')),
            ],
            options={
                'verbose_name': '\u041f\u043b\u0430\u0442\u0435\u0436',
                'verbose_name_plural': '\u041f\u043b\u0430\u0442\u0435\u0436\u0438',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='wallet_id',
            field=models.CharField(default=b'1A28F667', max_length=8),
        ),
        migrations.AddField(
            model_name='payments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c'),
        ),
    ]
