# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-04 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20180904_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='txn_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='\u041a\u043b\u044e\u0447 \u0442\u0440\u0430\u043d\u0437\u0430\u043a\u0446\u0438\u0438'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wallet_id',
            field=models.CharField(default=b'43CEDE07', max_length=8),
        ),
    ]
