# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-04 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20180904_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='price1',
        ),
        migrations.AddField(
            model_name='video',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Products', verbose_name='\u0423\u0440\u043e\u0432\u0435\u043d\u044c'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.PositiveIntegerField(verbose_name='\u0426\u0435\u043d\u0430 \u043f\u0440\u043e\u0434\u0443\u043a\u0442\u0430 \u0441 \u0443\u0447\u0435\u0442\u043e\u043c \u0434\u043b\u044f \u043a\u043e\u043c\u043f\u0430\u043d\u0438\u0438'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wallet_id',
            field=models.CharField(default=b'F48EAA5A', max_length=8),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='video/', verbose_name='\u0412\u0438\u0434\u0435\u043e'),
        ),
    ]
