# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-04 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20180904_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionkeys',
            name='is_confirmed_by_admin',
        ),
        migrations.RemoveField(
            model_name='transactionkeys',
            name='is_confirmed_by_user',
        ),
        migrations.RemoveField(
            model_name='transactionkeys',
            name='key_for_user',
        ),
        migrations.AlterField(
            model_name='user',
            name='wallet_id',
            field=models.CharField(default=b'A935E3E2', max_length=8),
        ),
    ]
