# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-16 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_auto_20180913_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mobilnik',
        ),
        migrations.AddField(
            model_name='user',
            name='account',
            field=models.CharField(max_length=255, null=True, verbose_name='\u0420\u0430\u0441\u0447\u0435\u0442\u043d\u044b\u0439 \u0441\u0447\u0435\u0442'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wallet_id',
            field=models.CharField(default=b'55822A16', max_length=8),
        ),
    ]
