# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-20 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_auto_20180917_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='points',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, null=True, verbose_name='\u0411\u0430\u043b\u043b\u044b'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wallet_id',
            field=models.CharField(default=b'89FC52E9', max_length=8),
        ),
    ]
