# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-21 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_auto_20180921_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wallet_id',
            field=models.CharField(default=b'3E3E0FC4', max_length=8),
        ),
    ]
