# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-21 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_auto_20180921_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wallet_id',
            field=models.CharField(default=b'A2AB940C', max_length=8),
        ),
    ]
