# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-21 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_auto_20180921_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wallet_id',
            field=models.CharField(default='53577284', max_length=8, unique=True),
        ),
    ]
