# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-22 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_auto_20180921_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wallet_id',
            field=models.CharField(default='59452327', max_length=8, unique=True),
        ),
    ]
