# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-01 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_auto_20180927_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashrequests',
            name='points',
            field=models.PositiveIntegerField(choices=[(300, '300'), (500, '500'), (700, '700'), (2000, '2000'), (1000, '1000'), (2000, '2000')], verbose_name='\u0411\u043e\u043d\u0443\u0441\u044b'),
        ),
    ]
