# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-02 17:34
from __future__ import unicode_literals

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='preview',
            field=models.ImageField(null=True, upload_to='', verbose_name='Картинка новости'),
        ),
        migrations.AlterField(
            model_name='sociallinks',
            name='icon',
            field=models.FileField(upload_to='', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
