# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-12 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_auto_20181003_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=255, null=True, verbose_name='\u0410\u0434\u0440\u0435\u0441'),
        ),
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.CharField(max_length=255, null=True, verbose_name='\u0420\u0430\u0439\u043e\u043d'),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_id',
            field=models.CharField(max_length=255, null=True, verbose_name='\u041f\u0430\u0441\u043f\u043e\u0440\u0442 \u0441\u0435\u0440\u0438\u0438'),
        ),
    ]
