# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-22 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_auto_20180922_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wallet_id',
            field=models.CharField(default='27631878', max_length=8, unique=True),
        ),
    ]
