# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-13 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='INN',
            field=models.CharField(max_length=255, null=True, verbose_name='\u0418\u041d\u041d'),
        ),
    ]
