# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-23 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_auto_20180923_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='caption',
        ),
        migrations.AddField(
            model_name='video',
            name='keycode',
            field=models.CharField(max_length=5, null=True, verbose_name='\u041a\u043b\u044e\u0447\u0435\u0432\u043e\u0435 \u0441\u043b\u043e\u0432\u043e \u0438\u043b\u0438 \u0431\u0443\u043a\u0432\u0430'),
        ),
        migrations.AlterField(
            model_name='cashrequests',
            name='points',
            field=models.PositiveIntegerField(choices=[(1000, '1000'), (2000, '2000')], verbose_name='\u0411\u043e\u043d\u0443\u0441\u044b'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wallet_id',
            field=models.CharField(default='23051594', max_length=8, unique=True, verbose_name='\u041b\u0438\u0446\u0435\u0432\u043e\u0439 \u0441\u0447\u0435\u0442'),
        ),
    ]
