# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-12-21 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_news_viedo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='viedo',
            new_name='video',
        ),
    ]
