# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-12-21 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_auto_20181221_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashrequests',
            name='is_payed',
            field=models.BooleanField(default=False, verbose_name='Деньги переведены'),
        ),
    ]
