# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-02-13 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_cashrequests_is_payed'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='type',
            field=models.CharField(blank=True, choices=[('asisnur', 'Асис НУР'), ('mobilnik', 'Мобильник')], default='mobilnik', max_length=255, null=True, verbose_name='Вид терминала'),
        ),
    ]
