# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-24 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_auto_20180924_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(max_length=255, null=True, verbose_name='\u041e\u0431\u043b\u0430\u0441\u0442\u044c'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wallet_id',
            field=models.CharField(default='1880168', max_length=8, unique=True, verbose_name='\u041b\u0438\u0446\u0435\u0432\u043e\u0439 \u0441\u0447\u0435\u0442'),
        ),
    ]
